### ISSUE TITLE
[BUG] Error when applying AI scripts (OMD) to objects

### ISSUE THREAD

**Issue by MaeDaGoof** [hogsy/jaded#37]
## Summary
There are omd files that are used to give game objects AI functions, but in the 0.3.0 release, it does not work anymore.

## Steps to Reproduce
Taking whichever omd ai script file from the Technical bank, and dragging it to an object with no fuctions (oin and/or cin) attached to it in the 3d view.

## Expected Result
When dragging an omd file to an object, it should give said object the chosen AI functionality from the omd with no issues.

## Actual Result
It gives the assetion errors seen below and crashes the editor after ignoring both.

## Screenshots or Videos
![image](https://github.com/OldTimes-Software/jaded/assets/99543861/696fa7b8-c1e9-43dd-baf1-ffbf9364a54b)
![image](https://github.com/OldTimes-Software/jaded/assets/99543861/3cc03be2-a69f-4fd4-959f-af6e47cff107)

## Additional Information
I usually go the previous versions to add ai to objects, and after loading the maps with those objects in the 0.3.0 release, there is no issue, works like it should, so it is specficially a problem with applying the AI, not the object having it.

**Comment by hogsy** [comment]
Related to the changes introduced [here](https://github.com/OldTimes-Software/jaded/issues/20), and I just realised that's happening in the new code we introduced, so we'll need to investigate what's going on there. As mentioned on Discord, I probably won't get to it until December, so just use the prior stable release for now.

**Comment by hogsy** [comment]
Mae has confirmed the issue appears to be fixed but will let me know if anything else pops up. Will close this one.
