### ISSUE TITLE
(BUG) jaded 2023-07-23 Importing tga file to the bf folder

### ISSUE THREAD

**Issue by gamemasterzen** [hogsy/jaded#38]
when i open jaded and i was thinking to make a texture mod for a game called imagine champion rider and i edited a tga file with gimp. when i try to import my tga to the texture folder its says
JADED Exception!
A exception has been thrown. Click YES to diagnose with the debugger. Click NO to attempt continuing.

**Comment by hogsy** [comment]
Please include the TGA you're trying to import. And next time, please use the template that's provided to you upon creating a new ticket - it's there for a reason.

**Comment by hogsy** [comment]
Had provided a work-around; for anyone else curious, just disable RLE compression. I'm working on a proper solution [here](https://github.com/hogsy/jaded-mirror/tree/feature/improved_image_support) (alongside support for other formats) and will close once completed.

**Comment by hogsy** [comment]
I'm just going to close it now - fixed [here](https://github.com/hogsy/jaded-mirror/commit/98690734756350582f97d213c8bfa207f06c2785). Will be released as part of 0.3.0
