### ISSUE TITLE
[BUG] Levels not loading

### ISSUE THREAD

**Issue by Artelleni** [hogsy/jaded#40]
## Summary
trying to make a new level and while doing it right in the newest version i keep getting a indices too big error 
in a older version it still does not work yet gives clearer error message 

## Steps to Reproduce
I made a new level and added _basic_global and _basic_rayman to a .wol file i had made
i attempted to load the level with just the necessary basics in it and still get a crash.
## Expected Result
What should happen when the steps are followed.
The Level should load properly without an issue.
## Actual Result
What actually happens when the steps are followed.
instead i get the repeated indices too big error.
and in the version before the latest one i get this specific log message 
STRDATA_IncreaseStringBuffer : increase to 96 string
STRDATA_IncreaseLetterBuffer : increase to 3072 char
## Screenshots or Videos
Any relevant screenshots or videos that can help illustrate the bug.
![image](https://github.com/OldTimes-Software/jaded/assets/53300422/01aef9c4-4fa2-414e-be11-29b12f568405)

## Additional Information
it may be an issue due to my computers hardware

**Comment by hogsy** [comment]
Thanks for the report. There are a lot of issues I've resolved in the upcoming 0.3.0 release, so if it's not fixed there I'll look into it for the release following.

**Comment by hogsy** [comment]
Hi @Artelleni, apologies for the wait for this one. The errors you mentioned are occurring on the script-side, and in the original version of Jade the error messages weren't entirely helpful.

You'll find a pre-release build of Jaded which has slightly more verbose error messages for script errors. If you could reproduce the problem and then show me the prompt you see, and then click onto 'OK' with another screenshot of what the script editor shows, that would be really helpful.

[hogsy_jade-patch_20240224.zip](https://github.com/hogsy/jaded/files/14393202/hogsy_jade-patch_20240224.zip)

Let me know if you encounter any other problems.

**Comment by hogsy** [comment]
No response in almost a month, closing. If you manage to reproduce it again, please let me know.
