### ISSUE TITLE
[BUG] MAJOR BUG: Exception bug for every Trigger option for most objects.

### ISSUE THREAD

**Issue by Moonlow0** [hogsy/jaded#49]
After seeing the Bipod's Trigger_Death option crash the editor. I discovered that almost all objects with Trigger options crash the editor with the same 'exception' error. Many things like the Bipod's Trigger Death option and a lot more objects just crash the editor. I'm not really sure if it is just my Bigfile or the editor itself to be honest. I don't know much more other than this is a **MAJOR** bug because it means that most objects won't work when adding them.

**Comment by hogsy** [comment]
Until you start using the template provided, I'm just going to automatically close these going forward.

If you decide to raise it again, please provide the crash dump, display the exception message and provide some clear steps.

**Comment by Moonlow0** [comment]
> Until you start using the template provided, I'm just going to automatically close these going forward.
> 
> If you decide to raise it again, please provide the crash dump, display the exception message and provide some clear steps.

I just don't know what to even say about the bug. It is all I have to say and all I know. Plus. You already have the dump file I sent you I think.
