### ISSUE TITLE
[BUG] Wont work with just dance 1

### ISSUE THREAD

**Issue by Dingoguts** [hogsy/jaded#56]
Summary
For some reason, jaded wont work with the WD_bin_wii.bf file from just dance 1

Steps to Reproduced
Open WD_bin_wii.bf with run_editor.bat

Expected Result:
if you open it in the jaded editor using run_editor.bat, then you should be able to open WD_bin_wii.bf and use it inside the editor
Actual Result:
if you open it in the jaded editor using run_editor.bat,  you will get an error message that states: "error while reading file"

Additional Information
Editor might come into an issue while reading the file because it has the file, FlashPackages.bin, which can only be read in a flash editor

**Comment by MaeDaGoof** [comment]
Retail BF files do not work with Jade/Jaded, they have been fully compiled and Jade can no longer access anything in those BFs outside of the folder structures. Only the leaked Rayman 4 Prototype BF alongside its patches and modifications can work with it, cause it is a development BF

**Comment by Dingoguts** [comment]
thanks

**Comment by Peinguy** [comment]
Although this is closed I want to ask something else related (Cuz I'm an idiot)
I have what appears to be a retail bf, the one for the wii copy or Rayman 4
It loads in the fs properly, but all files fail to load. Is this also because of the compiling?

**Comment by hogsy** [comment]
> Although this is closed I want to ask something else related (Cuz I'm an idiot) I have what appears to be a retail bf, the one for the wii copy or Rayman 4 It loads in the fs properly, but all files fail to load. Is this also because of the compiling?

Yup, same reason. It's a retail BF, and the data within has gone through a "binarisation" process.

You can use [Ray1Map](https://github.com/BinarySerializer/Ray1Map) to produce a BF with the process reversed to a limited capacity.

**Comment by Peinguy** [comment]
Okay, how do I use Ray1Map again? The wii version isn't one of the supported versions
